[SERVICE]
	Flush        1
	Log_Level    info

[INPUT]
	Name         opentelemetry
	Listen       0.0.0.0
	Port         4319
	Tag          healthchecker
	Logs_Metadata_Key otlp_meta

[FILTER]
	Name         modify
	Match        "*"
	Copy         metadata.otlp.attributes.node node_name

[FILTER]
	Name         lua
	Match        healthchecker
	Call         process_otlp_attributes
	Code         function process_otlp_attributes(tag, timestamp, group, metadata, record) local attributes = metadata["otlp"] and metadata["otlp"]["attributes"] if attributes and attributes["v"] ~= nil then record["v"] = tostring(attributes["v"]) end return tag, timestamp, metadata, record end

[FILTER]
	Name         rewrite_tag
	Match        healthchecker
	Rule         $otlp.attributes.node ^([0-9]+)$ healthchecks.$1.eu-central false

[OUTPUT]
	Name         stdout
	Match        *
